exec-once = hypridle
exec-once = mako
exec-once = waybar
exec-once = swaybg -i ~/.config/hypr/wallpaper.png -m fill
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# >>> managed by a-la-carchy power-profile
exec-once = /home/jonathan/.config/hypr/scripts/power-profile-default.sh
# <<< managed by a-la-carchy power-profile
