general {
    lock_cmd = omarchy-lock-screen                         # lock screen and 1password
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on  # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

listener {
    timeout = 600                                             # 2.5min
    on-timeout = pidof hyprlock || omarchy-launch-screensaver # start screensaver (if we haven't locked already)
}

listener {
    timeout = 30
    # on-timeout = pidof hyprlock && brightnessctl -sd '*::kbd_backlight' set 0 && hyprctl dispatch dpms off
    # on-resume = pidof hyprlock && brightnessctl -rd '*::kbd_backlight' && hyprctl dispatch dpms on
}

listener {
    timeout = 900                      # 5min
    on-timeout = loginctl lock-session # lock screen when timeout has passed
}
